### ISSUE TITLE
Can't find P-51K in China TT

### ISSUE THREAD

**Issue by blyatman996** [booooohdan/flutter_wt_versus#35]
Can't find P-51K in the Chinese tech tree.
![Screenshot_2022-06-26-22-06-02-16_304b461abad4d11f3b6bfd31150fb429.jpg](https://user-images.githubusercontent.com/65327589/175818085-0ddff1ed-4e3d-46a5-950b-43edabc6e648.jpg)

Could you add it?

Regards.

**Comment by booooohdan** [comment]
Thanks for your submission. I have a problem getting data for 'Su-8' and 'P-51K (China)'. If this issue will touches more planes we add some workaround, but now we have task with a bigger priority
