### ISSUE TITLE
BMP-2M

### ISSUE THREAD

**Issue by KiwiWT** [booooohdan/flutter_wt_versus#36]
The main weapon is shown as the 30mm grenade launcher not the 30mm autocannon.

**Comment by booooohdan** [comment]
According to https://wiki.warthunder.com/BMP-2M, the main weapon is **30 mm automatic grenade launcher AG-30**
![image](https://user-images.githubusercontent.com/30977443/187645809-13d479a0-0bee-484b-87ce-a15489d7f340.png)
