### ISSUE TITLE
Top speeds at specific altitudes

### ISSUE THREAD

**Issue by nsgallup** [booooohdan/flutter_wt_versus#5]
I really liked how the previous version of the app displayed the top speed of aircraft at sea level and at 5000 meters. This allowed for meaningful comparison of aircraft speed. Please considering bringing this back.

Edit: As well there is no indication of thrust to weight for aircraft which was a useful feature previously.

**Comment by booooohdan** [comment]
In the previous version of the app, we measured the speed manually. This is time-consuming and inaccurate, so we abandoned this method. Unfortunately.

Thanks for the reminder. We will add the power-weight ratio in the next update
